name: pcsc_wrapper
description: "Dart PCSC Wrapper Library"
repository: https://github.com/devrim-oguz/dart_pcsc_wrapper
version: 3.0.0

platforms:
  linux:

environment:
  sdk: ^3.10.3

dependencies:
  ffi: ^2.1.4
  tuple: ^2.0.2

dev_dependencies:
  ffigen: ^20.1.1