name: pcsc_wrapper
description: "Dart PCSC Wrapper Library"
repository: https://github.com/devrim-oguz/dart_pcsc_wrapper
version: 4.0.1

platforms:
  linux:
  macos:

environment:
  sdk: ^3.10.4

dependencies:
  ffi: ^2.1.4

dev_dependencies:
  ffigen: ^20.1.1